FROM centos:7.9.2009 as builder
ARG YB_VERSION=2.9.1.0
ARG USERNAME=yugabyte

RUN yum update -y \
    && yum install -y curl wget \
    && wget https://downloads.yugabyte.com/yugabyte-${YB_VERSION}-linux.tar.gz -O /yugabyte-${YB_VERSION}-linux.tar.gz \
    && mkdir -p /home/${USERNAME} \
    && tar xvfz /yugabyte-${YB_VERSION}-linux.tar.gz -C /home/${USERNAME} --strip 1 \
    && /home/${USERNAME}/bin/post_install.sh

FROM centos:7.9.2009
ARG GID=1060
ARG GROUPNAME=yugabyte
ARG UID=1060
ARG USERNAME=yugabyte
ARG YB_VERSION=2.9.1.0

RUN groupadd -g ${GID} ${GROUPNAME} \
    && useradd -m -d /home/${USERNAME} -g ${GID} -u ${UID} -s /bin/bash ${USERNAME}

COPY --chown=${USERNAME}:${GROUPNAME} docker-entrypoint.sh /docker-entrypoint.sh
COPY --from=builder --chown=${USERNAME}:${GROUPNAME} /home/${USERNAME} /home/${USERNAME}

RUN yum update -y \
    && yum install -y openssl ca-certificates \
    && chmod +x /docker-entrypoint.sh \
    && mkdir -p /mnt/{master,tserver} \
    && chown -R ${USERNAME}:${GROUPNAME} /mnt \
    && ln -s /home/${USERNAME}/bin/yb-admin /usr/local/bin/yb-admin \
    && ln -s /home/${USERNAME}/bin/yb-ts-cli /usr/local/bin/yb-ts-cli \
    && ln -s /home/${USERNAME}/bin/ycqlsh /usr/local/bin/ycqlsh \
    && ln -s /home/${USERNAME}/bin/ysqlsh /usr/local/bin/ysqlsh \
    && ln -s /home/${USERNAME}/bin/yugabyted /usr/local/bin/yugabyted

USER ${USERNAME}

ENTRYPOINT ["/docker-entrypoint.sh"]
