FROM centos:7.9.2009 as builder
ARG YB_VERSION=2.13.0.1-b2
ARG USERNAME=yugabyte

RUN YB_VERSION_ONLY=$(echo ${YB_VERSION} | awk -F- '{print $1}') \
    && yum update -y \
    && yum install -y curl wget \
    && wget https://downloads.yugabyte.com/releases/${YB_VERSION_ONLY}/yugabyte-${YB_VERSION}-linux-x86_64.tar.gz -O /yugabyte-${YB_VERSION_ONLY}-linux.tar.gz \
    && mkdir -p /home/${USERNAME} \
    && tar xvfz /yugabyte-${YB_VERSION_ONLY}-linux.tar.gz -C /home/${USERNAME} --strip 1 \
    && /home/${USERNAME}/bin/post_install.sh

FROM alpine:3.15
ARG GID=1060
ARG GROUPNAME=yugabyte
ARG UID=1060
ARG USERNAME=yugabyte

RUN apk add --no-cache bash gawk sed grep bc coreutils openssl ca-certificates \
    && addgroup -g ${GID} ${GROUPNAME} \
    && adduser -u ${UID} -G ${GROUPNAME} -D -s /bin/bash ${USERNAME}

COPY --chown=${USERNAME}:${GROUPNAME} docker-entrypoint.sh /docker-entrypoint.sh
COPY --from=builder --chown=${USERNAME}:${GROUPNAME} /home/${USERNAME} /home/${USERNAME}

SHELL ["/bin/bash", "-c"]

RUN echo "export PS1='[\u@\h \W]\$ '" >> /home/${USERNAME}/.bashrc \
    && chown ${USERNAME}:${GROUPNAME} /home/${USERNAME}/.bashrc \
    && chmod +x /docker-entrypoint.sh \
    && mkdir -p /mnt/{master,tserver} \
    && chown -R ${USERNAME}:${GROUPNAME} /mnt \
    && ln -s /home/${USERNAME}/bin/yb-admin /usr/local/bin/yb-admin \
    && ln -s /home/${USERNAME}/bin/yb-ts-cli /usr/local/bin/yb-ts-cli \
    && ln -s /home/${USERNAME}/bin/ycqlsh /usr/local/bin/ycqlsh \
    && ln -s /home/${USERNAME}/bin/ysqlsh /usr/local/bin/ysqlsh \
    && ln -s /home/${USERNAME}/bin/yugabyted /usr/local/bin/yugabyted

USER ${USERNAME}

ENTRYPOINT ["/docker-entrypoint.sh"]
