version: '3.9'

networks:
  yb-dbnet:
    name: yb-dbnet

volumes:
  vol_yb_tenant1_1:
    name: vol_yb_tenant1_1
  vol_yb_tenant1_2:
    name: vol_yb_tenant1_2
  vol_yb_tenant1_3:
    name: vol_yb_tenant1_3

services:

  envoy-yb-tenant1:
    image: envoyproxy/envoy:v1.19.1
    restart: unless-stopped
    container_name: envoy-yb-tenant1
    command: /usr/local/bin/envoy -c /etc/envoy/envoy-yb-tenant1.yaml #-l debug
    ports:
      - 35433:35432
    volumes:
      - type: bind
        source: ./etc/envoy/envoy-yb-tenant1.yaml
        target: /etc/envoy/envoy-yb-tenant1.yaml
    networks:
      - yb-dbnet

  yb-tserver-tenant1-1:
    image: ${YB_IMAGE}
    container_name: yb-tserver-tenant1-1
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_tenant1_1:${YB_MOUNT_PREFIX}/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-tserver",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-tenant1-1:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=tenant1",
      "--placement_zone=tenant1a",
      "--stop_on_parent_termination",
      "--undefok=stop_on_parent_termination",
      "${YB_EXT_FLAGS}"]
    deploy:
      resources:
        limits:
          cpus: "${YB_RESOURCES_CPU_LIMIT}"
          memory: "${YB_RESOURCES_MEM_LIMIT}"
        reservations:
          cpus: "${YB_RESOURCES_CPU_RESERVATION}"
          memory: "${YB_RESOURCES_MEM_RESERVATION}"

  yb-tserver-tenant1-2:
    image: ${YB_IMAGE}
    container_name: yb-tserver-tenant1-2
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_tenant1_2:${YB_MOUNT_PREFIX}/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-tserver",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-tenant1-2:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=tenant1",
      "--placement_zone=tenant1a",
      "--stop_on_parent_termination",
      "--undefok=stop_on_parent_termination",
      "${YB_EXT_FLAGS}"]
    deploy:
      resources:
        limits:
          cpus: "${YB_RESOURCES_CPU_LIMIT}"
          memory: "${YB_RESOURCES_MEM_LIMIT}"
        reservations:
          cpus: "${YB_RESOURCES_CPU_RESERVATION}"
          memory: "${YB_RESOURCES_MEM_RESERVATION}"

  yb-tserver-tenant1-3:
    image: ${YB_IMAGE}
    container_name: yb-tserver-tenant1-3
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_tenant1_3:${YB_MOUNT_PREFIX}/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-tserver",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-tenant1-3:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=tenant1",
      "--placement_zone=tenant1a",
      "--stop_on_parent_termination",
      "--undefok=stop_on_parent_termination",
      "${YB_EXT_FLAGS}"]
    deploy:
      resources:
        limits:
          cpus: "${YB_RESOURCES_CPU_LIMIT}"
          memory: "${YB_RESOURCES_MEM_LIMIT}"
        reservations:
          cpus: "${YB_RESOURCES_CPU_RESERVATION}"
          memory: "${YB_RESOURCES_MEM_RESERVATION}"
