version: '3.9'

networks:
  yb-dbnet:
    name: yb-dbnet

volumes:
  vol_yb_shared_1:
    name: vol_yb_shared_1
  vol_yb_shared_2:
    name: vol_yb_shared_2
  vol_yb_shared_3:
    name: vol_yb_shared_3

services:

  envoy-yb-shared:
    image: envoyproxy/envoy:v1.18.4
    restart: unless-stopped
    container_name: envoy-yb-shared
    command: /usr/local/bin/envoy -c /etc/envoy/envoy-yb-shared.yaml -l debug
    ports:
      - 35432:35432
    volumes:
      - type: bind
        source: ./etc/envoy/envoy-yb-shared.yaml
        target: /etc/envoy/envoy-yb-shared.yaml
    networks:
      - yb-dbnet

  yb-tserver-shared-1:
    image: local/yugabyte:2.9.0.0-b4
    container_name: yb-tserver-shared-1
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_shared_1:/mnt/data/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/ybdsh/bin/yb-tserver",
      "--fs_data_dirs=/mnt/data/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-shared-1:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--ysql_pg_conf_csv=shared_preload_libraries=dsh"]

  yb-tserver-shared-2:
    image: local/yugabyte:2.9.0.0-b4
    container_name: yb-tserver-shared-2
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_shared_2:/mnt/data/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/ybdsh/bin/yb-tserver",
      "--fs_data_dirs=/mnt/data/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-shared-2:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--ysql_pg_conf_csv=shared_preload_libraries=dsh"]

  yb-tserver-shared-3:
    image: local/yugabyte:2.9.0.0-b4
    container_name: yb-tserver-shared-3
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_shared_3:/mnt/data/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/ybdsh/bin/yb-tserver",
      "--fs_data_dirs=/mnt/data/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-shared-3:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--ysql_pg_conf_csv=shared_preload_libraries=dsh"]
