version: '3.9'

networks:
  yb-dbnet:
    name: yb-dbnet

volumes:
  vol_yb_master_1:
    name: vol_yb_master_1
  vol_yb_master_2:
    name: vol_yb_master_2
  vol_yb_master_3:
    name: vol_yb_master_3

services:

  yb-master-1:
    image: ${YB_IMAGE}
    container_name: yb-master-n1
    networks:
      - yb-dbnet
    ports:
      - 7000:7000
    volumes:
      - vol_yb_master_1:${YB_MOUNT_PREFIX}/master:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-master",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/master",
      "--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--rpc_bind_addresses=yb-master-n1:7100",
      "--logtostderr",
      "--minloglevel=1",
      "--placement_cloud=docker",
      "--replication_factor=3"]

  yb-master-2:
    image: ${YB_IMAGE}
    container_name: yb-master-n2
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_master_2:${YB_MOUNT_PREFIX}/master:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-master",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/master",
      "--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--rpc_bind_addresses=yb-master-n2:7100",
      "--logtostderr",
      "--minloglevel=1",
      "--placement_cloud=docker",
      "--replication_factor=3"]

  yb-master-3:
    image: ${YB_IMAGE}
    container_name: yb-master-n3
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_master_3:${YB_MOUNT_PREFIX}/master:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-master",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/master",
      "--master_addresses=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--rpc_bind_addresses=yb-master-n3:7100",
      "--logtostderr",
      "--minloglevel=1",
      "--placement_cloud=docker",
      "--replication_factor=3"]
