version: '3.9'

networks:
  yb-dbnet:
    name: yb-dbnet

volumes:
  vol_yb_tenant2_1:
    name: vol_yb_tenant2_1
  vol_yb_tenant2_2:
    name: vol_yb_tenant2_2
  vol_yb_tenant2_3:
    name: vol_yb_tenant2_3

services:

  envoy-yb-tenant2:
    image: envoyproxy/envoy:v1.19.1
    restart: unless-stopped
    container_name: envoy-yb-tenant2
    command: /usr/local/bin/envoy -c /etc/envoy/envoy-yb-tenant2.yaml #-l debug
    ports:
      - 35434:35432
    volumes:
      - type: bind
        source: ./etc/envoy/envoy-yb-tenant2.yaml
        target: /etc/envoy/envoy-yb-tenant2.yaml
    networks:
      - yb-dbnet

  yb-tserver-tenant2-1:
    image: local/yugabyte:2.9.0.0-b4
    container_name: yb-tserver-tenant2-1
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_tenant2_1:/mnt/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/yugabyte/bin/yb-tserver",
      "--fs_data_dirs=/mnt/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-tenant2-1:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=tenant2",
      "--placement_zone=tenant2a"]

  yb-tserver-tenant2-2:
    image: local/yugabyte:2.9.0.0-b4
    container_name: yb-tserver-tenant2-2
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_tenant2_2:/mnt/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/yugabyte/bin/yb-tserver",
      "--fs_data_dirs=/mnt/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-tenant2-2:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=tenant2",
      "--placement_zone=tenant2a"]

  yb-tserver-tenant2-3:
    image: local/yugabyte:2.9.0.0-b4
    container_name: yb-tserver-tenant2-3
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_tenant2_3:/mnt/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/yugabyte/bin/yb-tserver",
      "--fs_data_dirs=/mnt/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-tenant2-3:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=tenant2",
      "--placement_zone=tenant2a"]
