version: '3.9'

networks:
  yb-dbnet:
    name: yb-dbnet

volumes:
  vol_yb_shared_1:
    name: vol_yb_shared_1
  vol_yb_shared_2:
    name: vol_yb_shared_2
  vol_yb_shared_3:
    name: vol_yb_shared_3

services:

  envoy-yb-shared:
    image: envoyproxy/envoy:v1.19.1
    restart: unless-stopped
    container_name: envoy-yb-shared
    command: /usr/local/bin/envoy -c /etc/envoy/envoy-yb-shared.yaml #-l debug
    ports:
      - 35432:35432
    volumes:
      - type: bind
        source: ./etc/envoy/envoy-yb-shared.yaml
        target: /etc/envoy/envoy-yb-shared.yaml
    networks:
      - yb-dbnet

  yb-tserver-shared-1:
    image: ${YB_IMAGE}
    container_name: yb-tserver-shared-1
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_shared_1:${YB_MOUNT_PREFIX}/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-tserver",
      "--callhome_enabled=false",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-shared-1:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=base1",
      "--placement_zone=base1a",
      "--stop_on_parent_termination",
      "--undefok=stop_on_parent_termination",
      "${YB_EXT_FLAGS}",
      "--memory_limit_hard_bytes=${YB_MEMORY_LIMIT_HARD_BYTES_TSERVER}",
      "--default_memory_limit_to_ram_ratio=${YB_MEMORY_DEFAULT_LIMIT_TO_RAM_RATIO_TSERVER}",
      "--memory_limit_soft_percentage=${YB_MEMORY_LIMIT_SOFT_PERCENTAGE_TSERVER}",
      "--memory_limit_warn_threshold_percentage=${YB_MEMORY_LIMIT_WARN_THRESHOLD_PERCENTAGE_TSERVER}",
      "--mem_tracker_logging=${YB_MEM_TRACKER_LOGGING}",
      "--mem_tracker_log_stack_trace=${YB_MEM_TRACKER_LOG_STACK_TRACE}",
      "--mem_tracker_update_consumption_interval_us=${YB_MEM_TRACKER_UPDATE_CONSUMPTION_INTERVAL_US}"]
    environment:
      CONTAINER_WITHOUT_DSH: "true"
    deploy:
      resources:
        reservations:
          cpus: "${YB_RESOURCES_CPU_RESERVATION_TSERVER}"
          memory: "${YB_RESOURCES_MEM_RESERVATION_TSERVER}M"

  yb-tserver-shared-2:
    image: ${YB_IMAGE}
    container_name: yb-tserver-shared-2
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_shared_2:${YB_MOUNT_PREFIX}/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-tserver",
      "--callhome_enabled=false",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-shared-2:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=base1",
      "--placement_zone=base1a",
      "--stop_on_parent_termination",
      "--undefok=stop_on_parent_termination",
      "${YB_EXT_FLAGS}",
      "--memory_limit_hard_bytes=${YB_MEMORY_LIMIT_HARD_BYTES_TSERVER}",
      "--default_memory_limit_to_ram_ratio=${YB_MEMORY_DEFAULT_LIMIT_TO_RAM_RATIO_TSERVER}",
      "--memory_limit_soft_percentage=${YB_MEMORY_LIMIT_SOFT_PERCENTAGE_TSERVER}",
      "--memory_limit_warn_threshold_percentage=${YB_MEMORY_LIMIT_WARN_THRESHOLD_PERCENTAGE_TSERVER}",
      "--mem_tracker_logging=${YB_MEM_TRACKER_LOGGING}",
      "--mem_tracker_log_stack_trace=${YB_MEM_TRACKER_LOG_STACK_TRACE}",
      "--mem_tracker_update_consumption_interval_us=${YB_MEM_TRACKER_UPDATE_CONSUMPTION_INTERVAL_US}"]
    environment:
      CONTAINER_WITHOUT_DSH: "true"
    deploy:
      resources:
        reservations:
          cpus: "${YB_RESOURCES_CPU_RESERVATION_TSERVER}"
          memory: "${YB_RESOURCES_MEM_RESERVATION_TSERVER}M"

  yb-tserver-shared-3:
    image: ${YB_IMAGE}
    container_name: yb-tserver-shared-3
    networks:
      - yb-dbnet
    volumes:
      - vol_yb_shared_3:${YB_MOUNT_PREFIX}/tserver:rw
    command: [ "/docker-entrypoint.sh", "/home/${YB_USER}/bin/yb-tserver",
      "--callhome_enabled=false",
      "--fs_data_dirs=${YB_MOUNT_PREFIX}/tserver",
      "--enable_ysql",
      "--ysql_enable_auth",
      "--logtostderr",
      "--rpc_bind_addresses=yb-tserver-shared-3:9100",
      "--tserver_master_addrs=yb-master-n1:7100,yb-master-n2:7100,yb-master-n3:7100",
      "--placement_cloud=docker",
      "--placement_region=base1",
      "--placement_zone=base1a",
      "--stop_on_parent_termination",
      "--undefok=stop_on_parent_termination",
      "${YB_EXT_FLAGS}",
      "--memory_limit_hard_bytes=${YB_MEMORY_LIMIT_HARD_BYTES_TSERVER}",
      "--default_memory_limit_to_ram_ratio=${YB_MEMORY_DEFAULT_LIMIT_TO_RAM_RATIO_TSERVER}",
      "--memory_limit_soft_percentage=${YB_MEMORY_LIMIT_SOFT_PERCENTAGE_TSERVER}",
      "--memory_limit_warn_threshold_percentage=${YB_MEMORY_LIMIT_WARN_THRESHOLD_PERCENTAGE_TSERVER}",
      "--mem_tracker_logging=${YB_MEM_TRACKER_LOGGING}",
      "--mem_tracker_log_stack_trace=${YB_MEM_TRACKER_LOG_STACK_TRACE}",
      "--mem_tracker_update_consumption_interval_us=${YB_MEM_TRACKER_UPDATE_CONSUMPTION_INTERVAL_US}"]
    environment:
      CONTAINER_WITHOUT_DSH: "true"
    deploy:
      resources:
        reservations:
          cpus: "${YB_RESOURCES_CPU_RESERVATION_TSERVER}"
          memory: "${YB_RESOURCES_MEM_RESERVATION_TSERVER}M"
