{
 "title": "TServers: RPC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "RPC: accepted connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rpc_connections_accepted" }
   ]
  },
  {
   "title": "RPC: created connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rpc_connections_created" }
   ]
  },
  {
   "title": "RPC: alive connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "rpc_connections_alive" }
   ]
  }
 ]
}