{
 "title": "YSQL handler latency",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "SQL operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SELECT latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_SelectStmt_count"
    }
   ]
  },
  {
   "title": "INSERT latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_InsertStmt_count"
    }
   ]
  },
  {
   "title": "UPDATE latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_UpdateStmt_count"
    }
   ]
  },
  {
   "title": "DELETE latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_DeleteStmt_count"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Transaction latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_Transactions_count"
    }
   ]
  },
  {
   "title": "BEGIN latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_BeginStmt_count"
    }
   ]
  },
  {
   "title": "COMMIT latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_CommitStmt_count"
    }
   ]
  },
  {
   "title": "ROLLBACK latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_RollbackStmt_count"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Single shard transaction latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_Single_Shard_Transactions_count"
    }
   ]
  },
  {
   "title": "Aggregate pushdown latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_AggregatePushdowns_count"
    }
   ]
  },
  {
   "title": "Other statements latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "handler_latency_yb_ysqlserver_SQLProcessor_OtherStmts_count"
    }
   ]
  }
 ]
}