{
 "title": "System: Write Ahead Log writes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System: Bytes written to WAL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "log_bytes_logged{namespace_name=\"system\"}"
    }
   ]
  },
  {
   "title": "System: WAL file size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "log_wal_size{namespace_name=\"system\"}"
    }
   ]
  },
  {
   "title": "System: Log group commit batch size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "log_entry_batches_per_group_count{namespace_name=\"system\"}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "System: Log sync latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "log_sync_latency_count{namespace_name=\"system\"}"
    }
   ]
  },
  {
   "title": "System: Log append latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "log_append_latency_count" }
   ]
  },
  {
   "title": "System: Log group commit latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "log_group_commit_latency_count{namespace_name=\"system\"}"
    }
   ]
  },
  {
   "title": "System: Log roll latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "log_roll_latency_count{namespace_name=\"system\"}"
    }
   ]
  }
 ]
}