{
 "title": "TServers: System latency",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Read latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "handler_latency_yb_tserver_TabletServerService_Read{quantile=\"mean\"}"
    }
   ]
  },
  {
   "title": "p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "handler_latency_yb_tserver_TabletServerService_Read{quantile=\"p99\"}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "handler_latency_yb_tserver_TabletServerService_Read{quantile=\"max\"}"
    }
   ]
  },
  { "title": "Write latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "handler_latency_yb_tserver_TabletServerService_Write{quantile=\"mean\"}"
    }
   ]
  },
  {
   "title": "p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "handler_latency_yb_tserver_TabletServerService_Write{quantile=\"p99\"}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "handler_latency_yb_tserver_TabletServerService_Write{quantile=\"max\"}"
    }
   ]
  }
 ]
}